[2025-05-05T23:48:44.968+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:48:45.010+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:48:44.357466+00:00 [queued]>
[2025-05-05T23:48:45.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:48:44.357466+00:00 [queued]>
[2025-05-05T23:48:45.035+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-05T23:48:45.064+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-05-05 23:48:44.357466+00:00
[2025-05-05T23:48:45.080+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_deps', 'manual__2025-05-05T23:48:44.357466+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpktpdk9v5']
[2025-05-05T23:48:45.088+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask dbt_deps
[2025-05-05T23:48:45.089+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1135) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:48:45.092+0000] {standard_task_runner.py:72} INFO - Started process 1137 to run task
[2025-05-05T23:48:45.176+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:48:44.357466+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:48:45.341+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:48:44.357466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:48:44.357466+00:00'
[2025-05-05T23:48:45.343+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:48:45.379+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:48:45.383+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt deps --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-05-05T23:48:45.403+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:48:49.503+0000] {subprocess.py:93} INFO - [0m23:48:49  Running with dbt=1.8.7
[2025-05-05T23:48:49.787+0000] {subprocess.py:93} INFO - [0m23:48:49  Warning: No packages were found in packages.yml
[2025-05-05T23:48:49.803+0000] {subprocess.py:93} INFO - [0m23:48:49  Warning: No packages were found in packages.yml
[2025-05-05T23:48:50.471+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T23:48:50.509+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:48:50.510+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_deps, run_id=manual__2025-05-05T23:48:44.357466+00:00, execution_date=20250505T234844, start_date=20250505T234845, end_date=20250505T234850
[2025-05-05T23:48:50.537+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T23:48:50.570+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-05T23:48:50.574+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
